FROM maven:3.9-amazoncorretto-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests -B

FROM amazoncorretto:21-alpine
WORKDIR /app
COPY --from=build /app/target/app.jar app.jar
EXPOSE 5105
ENTRYPOINT ["java", "-jar", "app.jar"]
